package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AccountDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public double nextBillGenerationDate;
    public double currentBillGenerationDate;
    public double amountDue;
    public long todayDate;
    public String accountNumber;
    public String bankCode;
    public String branchCode;
    public String bankAccountName;
    public String idPayMeans;
    public boolean firstBillGenerated;

    public AccountDetails() {
    }




}