package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssignedAttributes implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
        public ImplRetrieveAssignedAttributesResponse implRetrieveAssignedAttributesResponse;

    public AssignedAttributes() {
    }




}