package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BankAccountDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public double amountDue;
    public String accountNumber;
    public String bankBranch;
    public boolean firstBillGenerated;
    

    public BankAccountDetails() {
    }




}