package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BillingArrangement implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String contactRole;
    public String barCustomerId;
    public String barRelatedFA;
    public String barName;
    public String barStatus;
    public String barId;

    public BillingArrangement() {
    }




}