package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BillingAccountDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String customerId;
    public String customerType;
    public String customerSubType;
    public String barName;
    public String billingAccountNumber;
    public String nickName;
    public List<Subscriber> subscribers;
    public String faId;
    public String contactRole;
    public String barContactRole;
    public boolean isInCatchup;
    public PhysicalAddress physicalAddress;
    public PayMeansDetails payMeansDetails;
    public String billDeliveryMethod;
    public String billType;
    public String faStatus;
    public long faStatusChangeDate;
    public boolean paInd;
    public String baStatus;
    public long faOpenDate;
    public String easyMobileInd;
    public PaginationInfo paginationInfo;
    public boolean complexServicesExists;

    public BillingAccountDetail() {
    }




}