package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import java.util.*;

public class ClientContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public Contact contact;
    public List<Customer> customers;
    public List<BillingArrangement> billingArrangements;
    public List<FinancialAccount> financialAccounts;
    public List<Subscription> subscriptions;
    public boolean complexServicesExists;
    

    public ClientContext() {
    }




}