package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactCustomerDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String customerId;
    public String customerName;
    public String customerType;
    public String customerSubType;
    public String contactRole;

    public ContactCustomerDetail() {
    }




}