package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactSubscriptionDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String primaryResource;
    public String subscriberId;
    public String subscriberStatus;
    public String contactRole;
    public String subscriberCustomerId;
    public String subscriberCustomerName;
    public String lineOfBusiness;
    public String subType;

    public ContactSubscriptionDetail() {
    }




}