package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactFinancialAccountDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String faId;
    public String faName;
    public String faStatus;
    public String contactRole;
    public String faCustomerId;
    public String faCustomerName;

    public ContactFinancialAccountDetail() {
    }




}