package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Contact implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String emailStatus;
    public String email;
    public String contactId;
    public String firstName;
    public String lastName;
    public String phone;
    public String indentType;
    public String indentValue;
    public long dateOfBirth;
    public String gender;

    public Contact() {
    }




}