package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContactBillingArrangementDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String barId;
    public String barName;
    public String barStatus;
    public String contactRole;
    public String barCustomerId;
    public String barCustomerName;
    public String faId;
    

    public ContactBillingArrangementDetail() {
    }




}