package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ContainedService implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    
     public List<Parameter2> parameters;
    public List<Link2> links;
    public String catalogItemID;
    public Object initialActivationDate;
    public String businessType;
    public List<PricePackage> pricePackages;
    public String catalogItemName;
    public String catalogItemDescription;
    public String id;
    public String status;
    public String serviceType;
    public ContainedService() {
    }




}