package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String customerObjId;
    public String customerId;
    public String customerType;
    public String customerSubType;
    public String contactRole;
    public String customerName; 

    public Customer() {
    }




}