package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Device implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String productCodeX8;
    public List<Parameter3> parameters;
    public String productSpecContainmentID;
    public String catalogItemName;
    public String catalogItemDescription;
    public String id;
    
    public Device() {
    }




}