package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorCounter implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Instance Id")
	private java.lang.Long instanceId;
	@org.kie.api.definition.type.Label("Error Count")
	private java.lang.Integer errorCount;

	@org.kie.api.definition.type.Label("Last Error Timestamp")
	private java.util.Date lastErrorTimestamp;

	@org.kie.api.definition.type.Label(value = "Node Instance Id")
	private java.lang.Long nodeInstanceId;

	public ErrorCounter() {
	}

	public java.lang.Long getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.Long instanceId) {
		this.instanceId = instanceId;
	}

	public java.lang.Integer getErrorCount() {
		return this.errorCount;
	}

	public void setErrorCount(java.lang.Integer errorCount) {
		this.errorCount = errorCount;
	}

	public java.util.Date getLastErrorTimestamp() {
		return this.lastErrorTimestamp;
	}

	public void setLastErrorTimestamp(java.util.Date lastErrorTimestamp) {
		this.lastErrorTimestamp = lastErrorTimestamp;
	}

	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Error Count: ");
		builder.append(errorCount);
		builder.append('\n');
		builder.append("Instance Id: ");
		builder.append(instanceId);
		builder.append('\n');
		builder.append("Last Error Timestamp: ");
		builder.append(lastErrorTimestamp);
		builder.append('\n');
		builder.append("Node Instance Id: ");
		builder.append(nodeInstanceId);
		builder.append('\n');
		return builder.toString();
	}

	public java.lang.Long getNodeInstanceId() {
		return this.nodeInstanceId;
	}

	public void setNodeInstanceId(java.lang.Long nodeInstanceId) {
		this.nodeInstanceId = nodeInstanceId;
	}

	public ErrorCounter(java.lang.Long instanceId,
			java.lang.Integer errorCount, java.util.Date lastErrorTimestamp,
			java.lang.Long nodeInstanceId) {
		this.instanceId = instanceId;
		this.errorCount = errorCount;
		this.lastErrorTimestamp = lastErrorTimestamp;
		this.nodeInstanceId = nodeInstanceId;
	}
}