package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinancialAccount implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String contactRole;
    public String faName;
    public String faId;
    public String faStatus;
    public String faCustomerId;
    

    public FinancialAccount() {
    }




}