package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplCustomerRoleDetailsResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public ImplCustomerRoleDetails implCustomerRoleDetails;

    public ImplCustomerRoleDetailsResponse() {
    }




}