package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplAccountBalanceRestOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String transactionId;
    public String accountId;
    public double balanceAmount;
    public double overdueAmount;
    public double lastMonthDue;
    

    public ImplAccountBalanceRestOutput() {
    }




}