package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplCustomerRoleDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String contactId;
    public String roleName;
    public String formattedAddressX9;
    public AccountDetails accountDetails;
    public String email;
    public String phone;

    public ImplCustomerRoleDetails() {
    }




}