package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplRetrieveBillingAccountsOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String transactionId;
    public List<BillingAccountDetail> billingAccountDetails;
    public boolean migratingAccount;

    public ImplRetrieveBillingAccountsOutput() {
    }




}