package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplPhysicalAddressDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
     public Country country;
    public String postcode;
    public String state;
    public String streetName;
    public String countryCode;
    public int isUnstructAddressX9;
    public String addressType;
    public String streetNumber;
    public String streetType;
    public String addressId;
    public String subUrb;
    public String formattedAddressX9;
    public String newFormattedAddressX9;
    public int isInternationalAddressX9;
    public String timeZoneOffset;
    public int isUnvalidatedAddress;

    public ImplPhysicalAddressDetails() {
    }




}