package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplEAddressType implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String objId;
    public boolean primary;
    public String eAddressType;

    public ImplEAddressType() {
    }




}