package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplContactPersonOutputResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public ImplContactPersonOutput implContactPersonOutput;

    public ImplContactPersonOutputResponse() {
    }




}