package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplX3NotificationPreferenceADT implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public NotificationPreferenceDetailsX1 notificationPreferenceDetailsX1;


    public ImplX3NotificationPreferenceADT() {
    }




}