package com.pam_poc.pam_poc;
import java.util.*;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplFindCallerByContactOutput implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String transactionId;
    public ContactDetails contactDetails;
    public List<ContactCustomerDetail> contactCustomerDetails;
    public List<ContactBillingArrangementDetail> contactBillingArrangementDetails;
    public List<ContactFinancialAccountDetail> contactFinancialAccountDetails;
    public List<ContactSubscriptionDetail> contactSubscriptionDetails;
    public ErrorADT errorADT;
    public boolean complexServicesExists;

    public ImplFindCallerByContactOutput() {
    }




}