package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplRetrieveAssignedAttributesResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String transactionId;
    public List<AssignedAttributesList> assignedAttributesList;
    public boolean success;
    public String assignedAttributesLevel;
    public boolean inContract;

    public ImplRetrieveAssignedAttributesResponse() {
    }




}