package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplContactPerson implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String birthDate;
    public String personGender;
    public String salutation;
    public String emailId;
    public String middleName;
    public String formattedName;
    public List<ImplX3NotificationPreferenceADT> implX3NotificationPreferenceADT;
    public ImplPhysicalAddressDetails implPhysicalAddressDetails;
    public List<PersonIdentificationDetail> personIdentificationDetails;
    public List<ImplElectronicAddress> implElectronicAddresses;
    public boolean isPrimary;
    public String hashedEmail;
    public String hashedPhone;
    public long birthDateNotParsed;
    public String contactObjId;
    public String residentialStatus;
    public String emailStatus;
    public String firstName;
    public String lastName;
    public String phone; 

    public ImplContactPerson() {
    }




}