package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ImplElectronicAddress implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public ImplEAddressType implEAddressType;
    public String value; 

    public ImplElectronicAddress() {
    }




}