package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Link implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String href;
    public String rel;

    public Link() {
    }




}