package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MigrationParams implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public boolean callLegacy;
    public boolean dashboardRequired;
    public boolean catchupPeriod;
    public long lastMigrationStartingTime;

    public MigrationParams() {
    }




}