package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationChannelX1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String notificationTitleX1;
    public String notificationRefIDX1;

    public NotificationChannelX1() {
    }




}