package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationPreferenceDetailsX1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public NotificationChannelX1 notificationChannelX1;
    public String notificationValueX1;

    public NotificationPreferenceDetailsX1() {
    }




}