package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaginationInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public int pageSize;
    public int pageCount;
    public int pageNumber;
    public int maxResultsCount;
    public boolean hasMore;

    public PaginationInfo() {
    }




}