package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Parameter3 implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String businessType;
    public String catalogId;
    public String valueName;
    public String name;
    
    

    public Parameter3() {
    }




}