package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PayMeansDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public BankAccountDetails bankAccountDetails;
    public String pcnStatus;
    public String paymentCategory;
    public String recurringFrequency;
    public int recurringFrequencyValue;
    public double recurringAmount;
    public String paymentMethod;

    public PayMeansDetails() {
    }




}