package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonIdentificationDetail implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String documentNumber;
    public String documentType;
    public String jurisdictionType;
    public String personId;
    public long validityEnd;
    public int validityStart;
    public String isPrincipal;
    public boolean isDefault; 

    public PersonIdentificationDetail() {
    }




}