package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Plan implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String displayName;
    public String catalogItemID;
    public String displayDescription;
    public String catalogItemName;
    public String catalogItemDescription;
    public String id;
  

    public Plan() {
    }




}