package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PricePackage implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String catalogItemID;
    public String catalogItemName;
    public String catalogItemDescription;
    public String id;
    public String status;

    public PricePackage() {
    }




}