package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Products implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public List<Product> products;

    public Products() {
    }




}