package com.pam_poc.pam_poc;
import java.util.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public Address address;
    public String serviceId;
    public String offeringDescription;
    public int subscriptionId;
    public String personId;
    public String paymentCategory;
    public String lob;
    public String offeringInstanceId;
    public String offeringId;
    public boolean shared;
    public List<Device> devices;
    public String offeringToProductId;
    public String spoName;
    public String spoDescription;
    public Plan plan;
    public String offeringName;
    public String serviceTypeX8;
    public boolean leasingPlanX8;
    public int remainingContractMonthsX8;
    public boolean hasPending;
    public boolean bundle;
    public String id;
    public String status;
    
    public List<Service> services;
    public List<Link3> links;
   
    public String catalogItemID;
    public String lineOfBusiness;
   
   
    public String orderActionReasonX8;
    public boolean ceaseActionAllowed;
    public boolean changeActionAllowed;
   
    

    public Product() {
    }




}