package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SampleRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	public SampleRequest() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public SampleRequest(java.lang.String name) {
		this.name = name;
	}
	
	@Override
	public String toString() {
		return "Content: [name=" + name + "]";
	}

}