package com.pam_poc.pam_poc;
import java.util.*;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Service implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public List<Parameter> parameters;
    public List<Link> links;
    public String catalogItemID;
    public Object initialActivationDate;
    public String businessType;
    public List<ContainedService> containedServices;
    public String catalogItemName;
    public String catalogItemDescription;
    public String id;
    public String status;
    public String serviceType;
    public List<PricePackage2> pricePackages;

    public Service() {
    }




}