package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Subscriber implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public int subscriberId;
    public int primaryInd;
    public Object subscriberActivationDate;
    public String subscriberStatus;
    public Object subscriberStatusChangeDate;
    public String subscriberType;
    public SubscriberName subscriberName;
    public SubscriberAddress subscriberAddress;
    public String subscriberCustomerId;
    public String serviceId;
    public String productId;
    public Plan plan;
    public String lob;
    public boolean shared;

    public Subscriber() {
    }




}