package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Subscription implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    public String contactRole;
    public String subType;
    public String primaryResource;
    public String subscriberId;
    public String subscriberStatus;
    public String subscriberCustomerId;
    public String lineOfBusiness;

    public Subscription() {
    }




}