package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubscriberName implements java.io.Serializable {

    static final long serialVersionUID = 1L;
     public String firstName;
    

    public SubscriberName() {
    }




}