package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubscriberAddress implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public int isUnstructAddressX9;
    public int isInternationalAddressX9;
    public int isUnvalidatedAddress;
    

    public SubscriberAddress() {
    }




}