package com.pam_poc.pam_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public String user;
    public String contactId;
    public String pid;

    public UserDetails() {
    }




}